const ERROR_CODES = {
  MOMENT_INVALID_ID: 'MOMENT_INVALID_ID',
  MOMENT_NOT_FOUND: 'MOMENT_NOT_FOUND',
  MOMENT_INVALID_OWNER: 'MOMENT_INVALID_OWNER',
  MOMENT_EMPTY: 'MOMENT_EMPTY',
  MOMENT_INVALID_TIME: 'MOMENT_INVALID_TIME',
  MOMENT_INVALID_ORIGIN: 'MOMENT_INVALID_ORIGIN',
  MOMENT_FORBIDDEN: 'MOMENT_FORBIDDEN',
  MOMENT_INVALID_TRANSITION: 'MOMENT_INVALID_TRANSITION',
  MOMENT_TRASHED: 'MOMENT_TRASHED',
  MOMENT_INVALID_CONTENT: 'MOMENT_INVALID_CONTENT',
  MOMENT_INVALID_CONTEXT: 'MOMENT_INVALID_CONTEXT',
  MOMENT_INVALID_ACCESS: 'MOMENT_INVALID_ACCESS',
  MOMENT_INVALID_LIFECYCLE: 'MOMENT_INVALID_LIFECYCLE',
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_INVALID: 'ASSET_INVALID',
  TRANSMISSION_INVALID: 'TRANSMISSION_INVALID',
  REPOSITORY_INVALID_RECORD: 'REPOSITORY_INVALID_RECORD',
  REPOSITORY_COLLECTION_NOT_ARRAY: 'REPOSITORY_COLLECTION_NOT_ARRAY',
  VAULT_INVALID_VIEW: 'VAULT_INVALID_VIEW',
}

class DomainError extends Error {
  /**
   * @param {string} code
   * @param {string} message
   */
  constructor(code, message) {
    super(message)
    this.name = 'DomainError'
    this.code = code
  }
}

function fail(code, message) {
  throw new DomainError(code, message)
}

module.exports = {
  ERROR_CODES,
  DomainError,
  fail,
}
