export class FamilyError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = 'FamilyError';
    this.code = code;
  }
}

export function isFamilyError(error: unknown): error is FamilyError {
  return error instanceof FamilyError;
}

export const FAMILY_ERROR = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  APPLE_TOKEN_INVALID: 'APPLE_TOKEN_INVALID',
  ALREADY_IN_FAMILY: 'ALREADY_IN_FAMILY',
  NOT_IN_FAMILY: 'NOT_IN_FAMILY',
  FORBIDDEN: 'FORBIDDEN',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_REVOKED: 'INVITE_REVOKED',
  INVITE_ALREADY_USED: 'INVITE_ALREADY_USED',
  FAMILY_DISSOLVED: 'FAMILY_DISSOLVED',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  BAD_REQUEST: 'BAD_REQUEST',
  MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',
  MEDIA_UNSUPPORTED: 'MEDIA_UNSUPPORTED',
  MEDIA_CORRUPT: 'MEDIA_CORRUPT',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MEDIA_WRITE_FAILED: 'MEDIA_WRITE_FAILED',
  SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
  SHARE_MEDIA_INCOMPLETE: 'SHARE_MEDIA_INCOMPLETE',
  SHARE_MEDIA_UNAVAILABLE: 'SHARE_MEDIA_UNAVAILABLE',
} as const;
